const DEFAULT_CONFIG={name:'Castila Village',location:'Perak - Jombang',phone:'628123456789',promos1:['Gratis biaya akad','DP ringan mulai 5%','Gratis kanopi rumah','Cashback Rp5 juta','Voucher furniture'],promos2:['Free biaya KPR','Gratis pagar rumah','Bonus kitchen set','Gratis AJB & SHM','Subsidi angsuran 3 bulan','Voucher pindahan'],chatTemplate:'Halo Admin Castila Village, saya {nama} dari {alamat} klik iklan di meta ads. Saya mau ambil promo {promo1} dan {promo2} yang saya dapat dari spin promo. Mohon info selanjutnya.'};
const byId=id=>document.getElementById(id);const backend=localStorage.getItem('castilaBackendUrl')||'';let config={...DEFAULT_CONFIG};let token=sessionStorage.getItem('castilaAdminToken');
byId('backendUrl').value=backend;toggleAdmin(Boolean(token));
function toggleAdmin(isLoggedIn){byId('loginPanel').style.display=isLoggedIn?'none':'block';byId('adminContent').style.display=isLoggedIn?'flex':'none';document.querySelectorAll('.tab-content').forEach(el=>el.style.display=isLoggedIn?'':'none');if(isLoggedIn)loadConfig()}
function jsonp(url){return new Promise((resolve,reject)=>{const callback=`castila_${Date.now()}`;window[callback]=data=>{delete window[callback];script.remove();resolve(data)};const script=document.createElement('script');script.src=`${url}${url.includes('?')?'&':'?'}callback=${callback}`;script.onerror=()=>{delete window[callback];script.remove();reject(new Error('Backend tidak bisa diakses'))};document.head.appendChild(script)})}
async function loadConfig(){try{const data=await jsonp(`${localStorage.getItem('castilaBackendUrl')}?action=config`);if(!data.ok)throw new Error(data.error);config={...DEFAULT_CONFIG,...data.config};fillConfig()}catch(error){byId('saveStatus').textContent=error.message}}
function fillConfig(){byId('settingName').value=config.name;byId('settingLocation').value=config.location;byId('settingPhone').value=config.phone;byId('promos1').value=config.promos1.join('\n');byId('promos2').value=config.promos2.join('\n');byId('chatTemplate').value=config.chatTemplate}
byId('loginButton').addEventListener('click',async()=>{const url=byId('backendUrl').value.trim();const password=byId('adminPassword').value;if(!url||!password){byId('loginMessage').textContent='URL backend dan password wajib diisi.';return}try{const data=await jsonp(`${url}?action=login&password=${encodeURIComponent(password)}`);if(!data.ok)throw new Error(data.error);localStorage.setItem('castilaBackendUrl',url);sessionStorage.setItem('castilaAdminToken',data.token);token=data.token;byId('loginMessage').textContent='';toggleAdmin(true)}catch(error){byId('loginMessage').textContent=error.message}});
byId('logout').addEventListener('click',()=>{sessionStorage.removeItem('castilaAdminToken');token='';toggleAdmin(false)});
byId('settingsForm').addEventListener('submit',event=>{event.preventDefault();const promos1=byId('promos1').value.split('\n').map(v=>v.trim()).filter(Boolean);const promos2=byId('promos2').value.split('\n').map(v=>v.trim()).filter(Boolean);if(promos1.length<2||promos2.length<2){alert('Spin promo harus minimal 2 pilihan.');return}const next={name:byId('settingName').value.trim(),location:byId('settingLocation').value.trim(),phone:byId('settingPhone').value.trim(),promos1,promos2,chatTemplate:byId('chatTemplate').value.trim()};fetch(localStorage.getItem('castilaBackendUrl'),{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain'},body:JSON.stringify({action:'saveConfig',token,config:next})}).catch(error=>console.error('Penyimpanan config gagal:',error));config=next;byId('saveStatus').textContent='Perubahan dikirim ke Spreadsheet ✓';setTimeout(()=>byId('saveStatus').textContent='',3000)});
document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.tab,.tab-content').forEach(el=>el.classList.remove('active'));tab.classList.add('active');byId(tab.dataset.tab).classList.add('active');if(tab.dataset.tab==='leads')loadLeads()}));
async function loadLeads(){try{const data=await jsonp(`${localStorage.getItem('castilaBackendUrl')}?action=leads&token=${encodeURIComponent(token)}`);if(!data.ok)throw new Error(data.error);const leads=data.leads||[];byId('leadCount').textContent=leads.length;const body=byId('leadsBody');body.innerHTML='';byId('emptyLeads').classList.toggle('hidden',leads.length>0);leads.slice().reverse().forEach(lead=>{const row=document.createElement('tr');row.innerHTML=`<td>${escapeHtml(lead.createdAt)}</td><td><strong>${escapeHtml(lead.name)}</strong></td><td>${escapeHtml(lead.phone)}</td><td>${escapeHtml(lead.address)}</td><td>${escapeHtml(lead.promo1)}<br>${escapeHtml(lead.promo2)}</td>`;body.appendChild(row)})}catch(error){byId('emptyLeads').textContent=error.message}}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]))}byId('exportCsv').addEventListener('click',()=>alert('Data leads tersimpan di Google Spreadsheet. Unduh langsung dari sheet Leads.'));
